// Generated by CoffeeScript 1.10.0
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.post('/*', function(req, res, next) {
    var error;
    if (req === null || req === "" || req === void 0) {
      error = "Request is undefined";
      console.log(error);
      return next();
    }
  });

  router.post('/*', function(req, res, next) {
    console.log(req.body);
    SMSDataArray.push(req.body, function(err) {
      if (err) {
        throw new Error("Add to array error");
      } else {
        res.statusCode = 200;
        console.log("FOR");
        return SMSDataArray.print(function(err) {
          if (err) {
            throw new Error("print error");
          }
        });
      }
    });
    res.render;
  });

  router.get('/list', function(req, res, next) {
    SMSDataArray.getListStringify(function(req) {
      return res.render('index', {
        title: 'Express',
        body: req
      });
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=addSMSData.js.map
