// Generated by CoffeeScript 1.10.0
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.use('/', function(req, res, next) {
    var err;
    if (req.header('token') !== '10A8D41FCA841705D8EFF4669578E512502') {
      err = new Error('Not authorized');
      err.status = 401;
      return next(err);
    } else {
      return next();
    }
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=auth.js.map
