// Generated by CoffeeScript 1.10.0
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/', function(req, res, next) {
    res.render('index', {
      title: 'Express',
      body: JSON.stringify(SMSDataArray)
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
