// Generated by CoffeeScript 1.10.0
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/', function(req, res, next) {
    res.render('index', {
      title: 'Express',
      body: req.balance
    });
  });

  router.post('/*', function(req, res, next) {
    var reqData;
    console.log(req.body);
    reqData = req.body;
    console.log(reqData);
    res.statusCode = 200;
    res.send();
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
