// Generated by CoffeeScript 1.10.0
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.post('/*', function(req, res, next) {
    var err;
    if (req === null || req === "" || req === void 0) {
      err = new Error('Bad request');
      err.status = 400;
      return next(err);
    }
    return next();
  });

  router.post('/', function(req, res, next) {
    console.log(req.body);
    return smsData.push(req.body, function(err) {
      if (err) {
        err = new Error('POST request error');
        err.status = 400;
        return next(err);
      } else {
        smsData.print(function(err) {
          if (err) {
            throw new Error("print error");
          }
        });
        res.statusCode = 200;
        return res.send();
      }
    });
  });

  router.get('/list', function(req, res, next) {
    smsData.getListStringify(function(req) {
      return res.render('index', {
        title: 'Express',
        body: req
      });
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=smsdata.js.map
