// Generated by CoffeeScript 1.10.0
(function() {
  var dbAdapter;

  dbAdapter = (function() {
    function dbAdapter() {}

    return dbAdapter;

  })();

}).call(this);

//# sourceMappingURL=dbAdapter.js.map
