// Generated by CoffeeScript 1.10.0
(function() {
  var app, auth, bodyParser, cookieParser, express, favicon, logger, path, routes, smsDataAdapter, smsdata, users;

  express = require('express');

  path = require('path');

  favicon = require('serve-favicon');

  logger = require('morgan');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  routes = require('./routes/index');

  users = require('./routes/users');

  smsdata = require('./routes/smsdata');

  auth = require('./routes/auth');

  smsDataAdapter = require('./model/smsDataAdapter');


  /*
  Create global objects
   */

  global.smsData = new smsDataAdapter();


  /*
  Main
   */

  app = express();

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(cookieParser());

  app.use(require('stylus').middleware(path.join(__dirname, 'public')));

  app.use(express["static"](path.join(__dirname, 'public')));


  /*
  Routes
   */

  app.use('/', routes);

  app.use('/', auth);

  app.use('/users', users);

  app.use('/smsdata', smsdata);


  /*
    Catch 404 and forward to error handler
   */

  app.use(function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    next(err);
  });

  if (app.get('env') === 'development') {
    app.use(function(err, req, res, next) {
      res.status(err.status || 500);
      res.render('error', {
        message: err.message,
        error: err
      });
    });
  }

  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: {}
    });
  });

  module.exports = app;

}).call(this);

//# sourceMappingURL=app.js.map
