// Generated by CoffeeScript 1.10.0
(function() {
  var SMSData;

  SMSData = (function() {
    function SMSData(name) {
      this.name = name;
    }

    SMSData.prototype.move = function(meters) {
      return alert(this.name + (" moved " + meters + "m."));
    };

    return SMSData;

  })();

}).call(this);

//# sourceMappingURL=SMSData.js.map
